#!/usr/bin/env python

from __future__ import print_function

import sys, os
import argparse


from pathlib import Path
from multiprocessing import freeze_support
from robot.libraries.OperatingSystem import OperatingSystem
from robot.libraries.Process import Process
from robot.libraries.DateTime import get_current_date
from robot.version import VERSION as RobotVersion

from robotremoteserver import (
    RobotRemoteMultiServer,
    stop_remote_server,
    test_remote_server,
)
from modules.ExpectInteractive import ExpectInteractive
from modules.ProcessLibrary import ProcessRemoteLibrary


# Unit-тесты. Взять от сюда https://github.com/robotframework/PythonRemoteServer

if not ("basestring" in vars() or "basestring" in globals()):
    basestring = str

__version_info__ = (1, 2, 0)
__version__ = ".".join((str(v) for v in __version_info__))


class ProcessRemoteLib(ProcessRemoteLibrary):

    ROBOT_LIBRARY_SCOPE = "GLOBAL"
    REMOTE_LIBRARY_ROUTE = "process"

    def __init__(self):
        super().__init__()


class OperatingSystemRemoteLib(OperatingSystem):
    """Example library to be used with Robot Framework's remote server.

    This documentation is visible in docs generated by `Libdoc`.
    """

    ROBOT_LIBRARY_SCOPE = "GLOBAL"

    def __init__(self) -> None:
        super().__init__()
        self.REMOTE_LIBRARY_ROUTE = "os"
        ...

    @staticmethod
    def get_current_date(
        time_zone="local", increment=0, result_format="timestamp", exclude_millis=False
    ):
        """Returns current local or UTC time with an optional increment.

        Arguments:
        - ``time_zone:``      Get the current time on this time zone. Currently only
                            ``local`` (default) and ``UTC`` are supported.
                            Has no effect if date is returned as an `epoch time`.
        - ``increment:``      Optional time increment to add to the returned date in
                            one of the supported `time formats`. Can be negative.
        - ``result_format:``  Format of the returned date (see `date formats`).
        - ``exclude_millis:`` When set to any true value, rounds and drops
                            milliseconds as explained in `millisecond handling`.

        Examples:
        | ${date} =       | Get Current Date |
        | Should Be Equal | ${date}          | 2014-06-12 20:00:58.946 |
        | ${date} =       | Get Current Date | UTC                     |
        | Should Be Equal | ${date}          | 2014-06-12 17:00:58.946 |
        | ${date} =       | Get Current Date | increment=02:30:00      |
        | Should Be Equal | ${date}          | 2014-06-12 22:30:58.946 |
        | ${date} =       | Get Current Date | UTC                     | - 5 hours |
        | Should Be Equal | ${date}          | 2014-06-12 12:00:58.946 |
        | ${date} =       | Get Current Date | result_format=datetime  |
        | Should Be Equal | ${date.year}     | ${2014}                 |
        | Should Be Equal | ${date.month}    | ${6}                    |
        """

        return get_current_date(time_zone, increment, result_format, exclude_millis)


def parse_manifest():
    """Добавление манифеста

    Returns:
        _type_: _description_
    """
    manifest_name = "manifest.json"
    manifest_default = {"os": "Unknown"}
    manifest_path = None
    try:

        for path in sys.path:
            candidate_path = Path(path) / manifest_name
            if candidate_path.is_file():
                manifest_path = candidate_path

        if not manifest_path:
            return manifest_default

        with open(manifest_path, "r", encoding="utf-8") as rd:
            manifest = rd.read()

        if manifest:
            from json import loads

            manifest = loads(manifest)

            manifest.get("os", "Unknown")
    except Exception:
        manifest = manifest_default

    return manifest


def parse_cli():
    man = parse_manifest()
    build_os = man.get("os", "Unknown")
    parser = argparse.ArgumentParser(
        description="XML-RPC server for performing remote procedures Robot Framework",
        add_help=False,
        prog="RLI agent (build_os: %s)" % build_os,
    )
    parser.add_argument(
        "-h",
        "--host",
        action="store",
        type=str,
        default="0.0.0.0",
        help="Server endpoint address, e.g. 0.0.0.0",
    )
    parser.add_argument(
        "-p",
        "--port",
        action="store",
        type=int,
        default=8270,
        help="Server port, 0-65536",
    )
    parser.add_argument(
        "-v",
        "--version",
        action="version",
        version=",\n ".join(
            [
                "Remote Linux Lib: " + __version__ + "",
                f"Robot Framework: {RobotVersion}",
                f"Build OS: {build_os}",
            ]
        ),
        help="Robot Framework version",
    )
    parser.add_argument(
        "--allow_remote_stop",
        action="store_true",
        default=True,
        help="Allow stopping the server via remote procedures",
    )
    parser.add_argument(
        "-d", "--debug", action="store_true", default=False, help="Turn on a debug mode"
    )
    parser.add_argument("--help", action="help", help=argparse.SUPPRESS)
    return parser.parse_args()


def test():
    def parse_args(script, *args):
        actions = {"stop": stop_remote_server, "test": test_remote_server}
        if not (0 < len(args) < 3) or args[0] not in actions:
            sys.exit("Usage:  %s {test|stop} [uri]" % os.path.basename(script))
        uri = args[1] if len(args) == 2 else "http://127.0.0.1:8270"
        if "://" not in uri:
            uri = "http://" + uri
        return actions[args[0]], uri

    action, uri = parse_args(*sys.argv)
    success = action(uri)
    sys.exit(0 if success else 1)


if __name__ == "__main__":

    # Для pyinstaller
    freeze_support()

    # Для запуска проверки доступности сервера
    if len(sys.argv) > 1 and sys.argv[1] in ["test", "stop"]:
        test()
    else:

        args = parse_cli()
        host = args.host
        port = args.port
        allow_rs = args.allow_remote_stop

        RobotRemoteMultiServer(
            OperatingSystemRemoteLib(),
            ProcessRemoteLib(),
            ExpectInteractive(),
            host=host,
            port=port,
            allow_remote_stop=allow_rs,
            debug_mode=args.debug,
        )
